export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>NeucamWebsiteTask2</title>
  <base href="/weather-dashboard-sample/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles-5INURTSO.css"><style ng-app-id="ng">.nav[_ngcontent-ng-c696357529]{display:flex;justify-content:space-around;padding:20px;background:#add8e6;font-weight:700}.nav[_ngcontent-ng-c696357529]   a[_ngcontent-ng-c696357529]{text-decoration:none}</style><style ng-app-id="ng">.counter-container[_ngcontent-ng-c2386692017]{text-align:center;margin-top:20px}.button-blue[_ngcontent-ng-c2386692017]{background-color:#00f;padding:10px}.button-grey[_ngcontent-ng-c2386692017]{background-color:gray}.button-red[_ngcontent-ng-c2386692017]{background-color:red}button[_ngcontent-ng-c2386692017]{margin:15px}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click"],[]);</script>
  <app-root ng-version="19.2.18" ngh="2" ng-server-context="ssg"><app-header _nghost-ng-c696357529 ngh="0"><div _ngcontent-ng-c696357529><nav _ngcontent-ng-c696357529 class="nav"><a _ngcontent-ng-c696357529 routerlink="/counter" routerlinkactive="active" href="/weather-dashboard-sample/counter" class="active" jsaction="click:;">Counter App 0</a><a _ngcontent-ng-c696357529 routerlink="/vatavaran" routerlinkactive="active" href="/weather-dashboard-sample/vatavaran" class jsaction="click:;">Weather App</a></nav></div></app-header><router-outlet></router-outlet><app-counter _nghost-ng-c2386692017 ngh="1"><div _ngcontent-ng-c2386692017 class="counter-container"><div _ngcontent-ng-c2386692017>Please click add/reset to start counter app</div><button _ngcontent-ng-c2386692017 class="button-blue" jsaction="click:;">Add</button><button _ngcontent-ng-c2386692017 class="button-blue" jsaction="click:;">Reset</button><!----></div></app-counter><!----></app-root>
<script src="polyfills-B6TNHZQ6.js" type="module"></script><script src="main-HMPUN5SO.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{},{"t":{"7":"t0"},"c":{"7":[]}},{"c":{"1":[{"i":"c2386692017","r":1}]}}]}</script></body></html>`;